#ifndef __MIKAN_LIB__
#define __MIKAN_LIB__

#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <ctype.h>
#include <string.h>
#include <time.h>
#include <direct.h>

#include <jstring.h>
#include <jtime.h>
#include <graph.h>

#include "MknDef.H"
#include "MknAsm.H"
#include "MknCur.H"
#include "MknCol.H"
#include "MknScr.H"
#include "MknGrf.H"
#include "MknSet.H"
#include "MknDrW.H"
#include "MknRun.H"

#endif
